In [28]:
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
from scipy import sparse

In [2]:
#import data
data = pd.read_csv("./data/combined_data_1.txt", header = None, names = ['cust_id', 'rating', 'date'])

In [22]:
print("full dataset:" + str(data.shape))
# To build cleaning logic, take the first 100,000 rows (0.5%)
df = data[:10000]
print("for cleaning logic purposes: " + str(df.shape))

full dataset:(24058263, 3)
for cleaning logic purposes: (10000, 3)


In [55]:
# Iterate and fill a list of python dicts. At end of loop, 
# put dict list in another pandas df. Want to look into more efficient method, but for now this'll do.

df_clean = pd.DataFrame({'rating' : [], 'cust_id' : [], 'movie_id' : []})
movie_id = -1
append_dict = {}
append_matrix = []
for row in df.itertuples():
    if(math.isnan(row[2])):
        movie_id = row[1][:-1]
        continue
    else:
        append_dict["rating"] = float(row[2])
        append_dict["cust_id"] = float(row[1])
        append_dict["movie_id"] = float(movie_id)
        append_matrix.append(append_dict.copy())

df_clean = df_clean.append(append_matrix,ignore_index=True)   

## NEED A DATASET TO INTERNAL ID CONVERSION

In [56]:
print(df_clean.head(10))

   rating    cust_id  movie_id
0     3.0  1488844.0       1.0
1     5.0   822109.0       1.0
2     4.0   885013.0       1.0
3     4.0    30878.0       1.0
4     3.0   823519.0       1.0
5     3.0   893988.0       1.0
6     4.0   124105.0       1.0
7     3.0  1248029.0       1.0
8     4.0  1842128.0       1.0
9     3.0  2238063.0       1.0


In [57]:
#plt.pcolormesh(df_clean)
#plt.yticks(np.arange(0.5, len(df_clean.index), 1), df_clean.index)
#plt.xticks(np.arange(0.5, len(df_clean.columns), 1), df_clean.columns)
#plt.show()

In [65]:
# Check for how many unique movies and customer
print(df_clean.shape)
print("Customers: " + str(df_clean["cust_id"].nunique()))
print("Movies: " + str(df_clean["movie_id"].nunique()))
print("overlap%: " + str(df_clean["cust_id"].nunique()/df.shape[0]))
print(df_clean["movie_id"].unique())
print(df_clean["cust_id"].unique())

(9992, 3)
Customers: 9619
Movies: 8
overlap%: 0.9619
[1. 2. 3. 4. 5. 6. 7. 8.]
[1488844.  822109.  885013. ... 1304395. 1468830. 1369078.]


In [64]:
try:
    df_sp = sparse.coo_matrix((df_clean["rating"], (df_clean["cust_id"], df_clean["movie_id"])), 
                          shape=(df_clean["cust_id"].nunique(), df_clean["movie_id"].nunique()))
except ValueError as err:
    print(err)
    pass
print(df_sp.todense())

row index exceeds matrix dimensions
[[3.000000e+00 1.488844e+06 1.000000e+00]
 [5.000000e+00 8.221090e+05 1.000000e+00]
 [4.000000e+00 8.850130e+05 1.000000e+00]
 ...
 [4.000000e+00 1.304395e+06 8.000000e+00]
 [3.000000e+00 1.468830e+06 8.000000e+00]
 [1.000000e+00 1.369078e+06 8.000000e+00]]
